[[pages]]
path = "pilot_devices/app_pilot_m22.py"
name = "M22"
icon = "ğŸ•¹ï¸"

[[pages]]
path = "pilot_devices/app_pilot_10250T.py"
name = "10250T"
icon = "ğŸ•¹ï¸"

[[pages]]
path = "pilot_devices/app_pilot_stacklights.py"
name = "Stacklights"
icon = "ğŸš¨"
